name: Auto Reply to Discussions
on:
  discussion_comment:
    types: [created]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-reply to new discussions
        uses: andymckay/create-discussion-comment@v1.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          discussion_number: ${{ github.event.discussion.number }}
          body: "Sehr geehrtes ByteConnect-Team \n Vielen Dank für Ihre Schnelle Antwort. Mithilfe dieser Werte werden wir mit Sicherheit die Geschäftsleitung überzeugen können auf Kündigungen zu verzichten. \n Danke und viele Grüße, Betriebsrat-BuchWurm"